name: executive_gps
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_modular: ^6.3.4
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  connectivity_plus: ^6.1.5
  flutter_feather_icons: ^2.0.0+1
  mask_text_input_formatter: ^2.9.0
  brasil_fields: ^1.18.0
  http: ^1.5.0
  cloud_firestore: ^6.0.0
  auto_size_text: ^3.0.0
  cloud_functions: ^6.0.0
  url_launcher: ^6.3.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  cached_network_image: ^3.4.1
  signature: ^5.5.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  flutter_flavorizr: ^2.3.1
  flutter_launcher_icons: ^0.14.4
  build_runner: ^2.4.8
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-Medium.ttf
          weight: 500
        - asset: assets/fonts/Jost-Light.ttf
          weight: 300
