// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD17q685gIFsKECW-R23i__9tf9lxekIi0',
    appId: '1:604118664223:android:13dc0e5ab9bd0bfdbbc12a',
    messagingSenderId: '604118664223',
    projectId: 'executive-gps-prod-a5f13',
    storageBucket: 'executive-gps-prod-a5f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBEXYDDDBxzGa-KAeypFJSe2ajcWhsI-o',
    appId: '1:604118664223:ios:574f8eacc3a7e8fabbc12a',
    messagingSenderId: '604118664223',
    projectId: 'executive-gps-prod-a5f13',
    storageBucket: 'executive-gps-prod-a5f13.firebasestorage.app',
    iosBundleId: 'br.com.executivegpsapp',
  );
}
