android {
    flavorDimensions += "flavor-type"

    productFlavors {
        dev {
            dimension "flavor-type"
            applicationId "com.example.executive_gps.dev"
            resValue "string", "app_name", "Dev Executive Gps"
        }
        prod {
            dimension "flavor-type"
            applicationId "com.example.executive_gps.prod"
            resValue "string", "app_name", "Executive Gps"
        }
    }
}